baseurl = "https://clopend.com/"
title = "Less is More"
author = "Clopend"
canonifyurls = true
languagecode = "zh-CN"
defaultContentLanguage = 'zh'

publishDir = "docs"

[params]
  sitename = "Less is More"
  slogan = ""
  github = "https://github.com/clopend"
  since = "2021"
  dateform = "2006-01-02"
